# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ angular-src ]
  pull_request:
    branches: [ angular-src ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: npm install
      run: npm install

    # Runs a single command using the runners shell
    - name: Production build
      run: ng build --prod --base-href https://samolego.github.io
    - name: Providing 404 page
      run: cp docs/index.html docs/404.html
    - name: Github Pages
      uses: crazy-max/ghaction-github-pages@v1.4.0
      with:
        target_branch: master
        build_dir: docs/
      env:
        GITHUB_PAT: ${{ secrets.pat }}
      
